### ISSUE TITLE
The default style (typeface) are not very readable

### ISSUE THREAD

**Issue by SuperJMN** [theunrepentantgeek/Markdown.XAML#12]
It seems that the default font that renders in the FlowDocument is not very readable. How should we change it? Setting the FontName in the `FlowDocumentScrollViewer` doesn't work?

Thanks in advance :)

**Comment by whistyun** [comment]
(I don't understand English well, so the sentence may be broken)

We should change ```Markdown.DocumentStyle```. This property value is set to ```FlowDocument.Style```.

See [gist](https://gist.github.com/whistyun/f1d58f54a5c805a837419e160575bb2e) for a short sample of Markdown.DocumentStyle.

If you want to change other items like headers, links and tables, See [MainWindow.xaml](https://github.com/theunrepentantgeek/Markdown.XAML/blob/master/src/Markdown.Xaml.Demo/MainWindow.xaml) and  [Markdown.Demo.Styles.Default.xaml](https://github.com/theunrepentantgeek/Markdown.XAML/blob/master/src/Markdown.Xaml.Demo/Markdown.Demo.Styles.Default.xaml)  in Markdown.Xaml.Demo.
