### ISSUE TITLE
Support Table

### ISSUE THREAD

**Issue by ychost** [theunrepentantgeek/Markdown.XAML#13]
Not Support Table Like 
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |

**Comment by theunrepentantgeek** [comment]
Tables are now supported, thanks to @whistyun - see PR #14 for details.
